name: GitHub Metrics

on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Identity & Activity (Left)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          template: terminal
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo

      - name: System Stats (Right)
        uses: lowlighter/metrics@latest
        with:
          # ENABLE DEBUGGING to see repository list in logs
          debug: yes
          
          filename: metrics.right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          template: terminal
          base: "" 
          config_timezone: America/Sao_Paulo
          config_order: languages, repositories, lines
          
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          plugin_repositories: yes
          plugin_repositories_featured: no
          
          plugin_lines: yes
          plugin_lines_sections: repositories
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          
          plugin_activity: no
          plugin_habits: no
          plugin_achievements: no
