name: GitHub Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
      CONFIG_TIMEZONE: America/Sao_Paulo
      BASE_CONFIG: header, activity, community, repositories

    steps:
      - name: Identity & Activity (Left)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.left.svg
          token: ${{ env.METRICS_TOKEN }}
          committer_token: ${{ env.METRICS_TOKEN }}
          template: terminal
          base: ${{ env.BASE_CONFIG }}
          config_timezone: ${{ env.CONFIG_TIMEZONE }}
          config_order: ""  # No specific order for left
      
      - name: System Stats (Right)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.right.svg
          token: ${{ env.METRICS_TOKEN }}
          committer_token: ${{ env.METRICS_TOKEN }}
          template: terminal
          base: ${{ env.BASE_CONFIG }}
          config_timezone: ${{ env.CONFIG_TIMEZONE }}
          config_order: languages, repositories, lines, stars

          # Unique configurations for the right metrics
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          plugin_repositories: yes
          plugin_repositories_featured: no
          plugin_repositories_pinned: 0
          plugin_repositories_order: featured, pinned, starred, random
          
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_delay: 0
          
          plugin_stars: yes
          plugin_stars_limit: 3
          
          # Disabled unwanted plugins
          plugin_isocalendar: no
          plugin_activity: no
          plugin_habits: no
          plugin_achievements: no
